SET NOCOUNT ON
DECLARE @Schema NVARCHAR(100) = 'org'
DECLARE @Table NVARCHAR(100) = 'OrgGroup'
DECLARE @sql NVARCHAR(MAX) =''
IF OBJECT_ID ('tempdb..#Nulls') IS NOT NULL DROP TABLE #Nulls

CREATE TABLE #Nulls ( 
ColumnName sysname, 
ColumnPosition int, 
NullCount int, 
LessThanOne int, 
LessThanTwo int, 
LessThanThree int
)

SELECT @sql += 'SELECT '''+COLUMN_NAME+''' AS ColumnName,
	'''+CONVERT(VARCHAR(5),ORDINAL_POSITION)+''' AS ColumnPosition, 
	SUM(CASE WHEN '+COLUMN_NAME+' IS NULL THEN 1 ELSE 0 END) CountNulls,
	SUM(CASE WHEN LEN('+COLUMN_NAME+') < 1 THEN 1 ELSE 0 END) LessThanOne,
	SUM(CASE WHEN LEN('+COLUMN_NAME+') < 2 THEN 1 ELSE 0 END) LessThanTwo,
	SUM(CASE WHEN LEN('+COLUMN_NAME+') < 3 THEN 1 ELSE 0 END) LessThanThree
	FROM '+QUOTENAME(TABLE_SCHEMA)+'.'+QUOTENAME(TABLE_NAME)+';'+ CHAR(10)
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = @Schema
AND TABLE_NAME = @Table

INSERT INTO #Nulls 
EXEC sp_executesql @sql

SELECT * 
FROM #Nulls
